#
## Base Alpine Linux based image with OpenJDK JRE only
#FROM openjdk:8-jre-alpine
## copy application WAR (with libraries inside)
#COPY target/MyHelloWorld-1.0.jar /app.jar
## specify default command
#CMD ["java", "-jar", "/app.jar"]
## Base Alpine Linux based image with OpenJDK JRE only

FROM openjdk:8
COPY ./target/com/demo/maven/ /tmp
WORKDIR /tmp
ENTRYPOINT ["java","App"]